spring:
  output:
      ansi:
          enabled: ALWAYS
  application:
    name: ecommerce-optic
  config:
    import: optional:file:.env[.properties]
  
  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop #update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    # Data Initialization
  sql:
    init:
      mode: always

  #spring.sql.init.data-locations=classpath:data.sql
  # Server Configuration
server:
  port: ${SERVER_PORT}
  #error: include-message: always
  
  # Logging Configuration
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#        springframework: DEBUG
#      com:
#        zaxxer:
#          hikari: DEBUG
  
cloudinary:
  cloud_name: ${CL_NAME}
  api_key: ${CL_API_KEY}
  api_secret: ${CL_API_SECRET}
#  secure: true
#  upload_preset: my_unsigned_preset
#  resource_type: image
#  default_transformations:
#    quality: auto
#    fetch_format: auto
#    crop: limit